"""initial

Revision ID: 9afad7a24837
Revises: 
Create Date: 2026-05-07 05:28:49.185919
"""

from alembic import op
import sqlalchemy as sa


revision = '9afad7a24837'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locals_id'), 'locals', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('marca', sa.String(length=255), nullable=True),
    sa.Column('presentacion', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('referral_code', sa.String(length=50), nullable=True),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barra', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcodes_codigo_barra'), 'barcodes', ['codigo_barra'], unique=True)
    op.create_index(op.f('ix_barcodes_id'), 'barcodes', ['id'], unique=False)
    op.create_table('price_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locals.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_correction_status', 'price_corrections', ['status'], unique=False)
    op.create_index('idx_price_correction_user', 'price_corrections', ['user_id'], unique=False)
    op.create_index(op.f('ix_price_corrections_id'), 'price_corrections', ['id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('verificado', sa.String(length=10), nullable=True),
    sa.Column('verificado_por', sa.Integer(), nullable=True),
    sa.Column('verificado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locals.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verificado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_product_local', 'prices', ['product_id', 'local_id'], unique=False)
    op.create_index('idx_price_product_local_verified', 'prices', ['product_id', 'local_id', 'verificado'], unique=False)
    op.create_index('idx_price_updated_by', 'prices', ['updated_by'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index('idx_price_updated_by', table_name='prices')
    op.drop_index('idx_price_product_local_verified', table_name='prices')
    op.drop_index('idx_price_product_local', table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_price_corrections_id'), table_name='price_corrections')
    op.drop_index('idx_price_correction_user', table_name='price_corrections')
    op.drop_index('idx_price_correction_status', table_name='price_corrections')
    op.drop_table('price_corrections')
    op.drop_index(op.f('ix_barcodes_id'), table_name='barcodes')
    op.drop_index(op.f('ix_barcodes_codigo_barra'), table_name='barcodes')
    op.drop_table('barcodes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_locals_id'), table_name='locals')
    op.drop_table('locals')
    # ### end Alembic commands ###

